language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "mictaege-github" # the organization name of the sonar account
    token:
      secure: $SONAR_TOKEN # the generated sonar security token
    branches: # sonar only analysis the main branch if no branches are selected
      - master
      - develop

branches:
  only:
    - master
    - develop

script:
  gradle clean test sonarqube
